[package]
description = "Madara utilities"
name = "mp-utils"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Starknet
starknet-core.workspace = true
starknet-crypto.workspace = true

# Other
anyhow.workspace = true
async-trait.workspace = true
crypto-bigint.workspace = true
futures.workspace = true
rand.workspace = true
rayon.workspace = true
serde.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
rstest.workspace = true
