[package]
name = "mc-sync"
description = "This crate is responsible to sync data"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[features]
default = []
m = []

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Madara
mc-block-import.workspace = true
mc-db.workspace = true
mc-gateway.workspace = true
mc-metrics.workspace = true
mc-telemetry.workspace = true
mp-block.workspace = true
mp-chain-config.workspace = true
mp-class.workspace = true
mp-convert.workspace = true
mp-gateway.workspace = true
mp-transactions.workspace = true
mp-utils.workspace = true

# Starknet
starknet-core.workspace = true
starknet-types-core.workspace = true
starknet_api.workspace = true


# Other
anyhow.workspace = true
futures = { workspace = true, default-features = true }
hyper.workspace = true
log.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "parking_lot",
  "test-util",
  "signal",
] }
url.workspace = true

[dev-dependencies]
httpmock.workspace = true
tempfile.workspace = true
rstest.workspace = true
regex.workspace = true
mc-db = { workspace = true, features = ["testing"] }
mc-block-import = { workspace = true, features = ["testing"] }
