[package]
name = "mc-metrics"
description = "Madara client prometheus service"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# Madara
mp-utils.workspace = true

# Other
anyhow.workspace = true
async-trait.workspace = true
hyper = "0.14"
log.workspace = true
prometheus.workspace = true
thiserror.workspace = true
tokio.workspace = true
